"""Helper: rewrite liq_impact_analysis.ipynb with minute-level event study."""
import json
from pathlib import Path

NB_PATH = Path(__file__).parent.parent / "notebooks" / "research" / "liq_impact_analysis.ipynb"

def cell(cell_type, source):
    base = {"cell_type": cell_type, "metadata": {}, "source": source}
    if cell_type == "code":
        base["execution_count"] = None
        base["outputs"] = []
    return base


cells = [

# ── 0 Markdown header ─────────────────────────────────────────────────────────
cell("markdown", [
    "# Liquidation Cascade Impact Analysis (REVISED — Minute-Level)\n",
    "**Analyst**: Jose (Risk Manager)  \n",
    "**Date**: 2026-03-23  \n",
    "**Asset**: BTCUSDT (Bybit Perpetual)  \n",
    "\n",
    "## Objective\n",
    "Event study on `liq_long_z` spikes — measure average BTC price trajectory  \n",
    "**+/- 60 minutes** (60 x 1m bars) around each high-magnitude long-liquidation event.\n",
    "\n",
    "## Methodology\n",
    "- **Event detection**: 1h structural features (lower-wick * volume proxy for liquidations)  \n",
    "- **Price trajectory**: 1m OHLCV fetched from Binance public REST API (no auth required)  \n",
    "- **Window**: t in [-60, +60] minutes = 121 bars at 1m resolution  \n",
    "- **Normalization**: divide each path by close at t=0 → relative % return  \n",
    "\n",
    "## Revision Note\n",
    "> Previous version used 1h bars (+/- 60h window = +/- 2.5 days).  \n",
    "> Revised to **1m bars (+/- 60 min)** per lead feedback to capture microstructure dynamics.",
]),

# ── 1 Imports & config ────────────────────────────────────────────────────────
cell("code", [
    "# -- 0. Imports & Configuration -----------------------------------------------\n",
    "import sys, warnings, time as _time, json as _json, urllib.request\n",
    "from pathlib import Path\n",
    "\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import matplotlib\n",
    "matplotlib.use('Agg')\n",
    "import matplotlib.pyplot as plt\n",
    "import matplotlib.gridspec as gridspec\n",
    "import matplotlib.ticker as mticker\n",
    "\n",
    "warnings.filterwarnings('ignore')\n",
    "\n",
    "# -- paths\n",
    "REPO_ROOT = Path().resolve()\n",
    "while not (REPO_ROOT / 'src').exists() and REPO_ROOT != REPO_ROOT.parent:\n",
    "    REPO_ROOT = REPO_ROOT.parent\n",
    "DATA_DIR = REPO_ROOT / 'data'\n",
    "OUT_DIR  = REPO_ROOT / 'reports'\n",
    "OUT_DIR.mkdir(parents=True, exist_ok=True)\n",
    "if str(REPO_ROOT) not in sys.path:\n",
    "    sys.path.insert(0, str(REPO_ROOT))\n",
    "\n",
    "# -- study parameters\n",
    "SYMBOL         = 'BTCUSDT'\n",
    "THRESHOLD      = 2.0\n",
    "THRESHOLD_HIGH = 3.0\n",
    "WINDOW         = 60       # +/- 60 minutes\n",
    "MIN_EVENT_GAP  = 3        # minimum 3h gap between events (1h index)\n",
    "Z_WINDOW       = 50\n",
    "BINANCE_BASE   = 'https://api.binance.com'\n",
    "\n",
    "print(f'Repo root : {REPO_ROOT}')\n",
    "print(f'Window    : +/-{WINDOW} minutes  ({WINDOW*2+1} 1m bars per event)')\n",
    "print(f'Threshold : liq_long_z > {THRESHOLD} sigma')\n",
]),

# ── 2 Load 1h structural data ─────────────────────────────────────────────────
cell("code", [
    "# -- 1. Load 1h Structural Data (event detection) ----------------------------\n",
    "t0 = _time.time()\n",
    "\n",
    "def _load_ohlcv_1h(data_dir):\n",
    "    files = sorted(data_dir.glob('training_BTCUSDT_1h_*.csv'))\n",
    "    if not files:\n",
    "        raise FileNotFoundError(f'No 1h OHLCV in {data_dir}')\n",
    "    frames = [pd.read_csv(f, usecols=['ts','open','high','low','close','volume'],\n",
    "                           encoding='utf-8') for f in files]\n",
    "    df = pd.concat(frames, ignore_index=True)\n",
    "    df['ts'] = pd.to_datetime(df['ts'], utc=True)\n",
    "    return df.drop_duplicates('ts').sort_values('ts').set_index('ts')\n",
    "\n",
    "def _load_aux(data_dir, glob_pat):\n",
    "    files = sorted(data_dir.glob(glob_pat))\n",
    "    if not files:\n",
    "        return None\n",
    "    df = pd.concat([pd.read_csv(f, encoding='utf-8') for f in files],\n",
    "                   ignore_index=True)\n",
    "    # Handle both 'ts' (string datetime) and 'ts_ms' (epoch ms) column names\n",
    "    if 'ts' in df.columns:\n",
    "        df['ts'] = pd.to_datetime(df['ts'], utc=True)\n",
    "    elif 'ts_ms' in df.columns:\n",
    "        df['ts'] = pd.to_datetime(df['ts_ms'].astype('int64'), unit='ms', utc=True)\n",
    "    else:\n",
    "        return None\n",
    "    return df.drop_duplicates('ts').sort_values('ts').set_index('ts')\n",
    "\n",
    "master   = _load_ohlcv_1h(DATA_DIR)\n",
    "taker_df = _load_aux(DATA_DIR, 'binance_taker_BTCUSDT_1h_*.csv')\n",
    "oi_df    = _load_aux(DATA_DIR, 'oi_BTCUSDT_1h_*.csv')\n",
    "\n",
    "for aux in [taker_df, oi_df]:\n",
    "    if aux is not None:\n",
    "        cols = [c for c in aux.columns if c not in master.columns]\n",
    "        master = master.join(aux[cols], how='left')\n",
    "\n",
    "print(f'1h master : {len(master):,} bars  '\n",
    "      f'({master.index.min().date()} to {master.index.max().date()})')\n",
    "print(f'Columns   : {master.columns.tolist()}')\n",
    "print(f'Loaded in {_time.time()-t0:.1f}s')\n",
]),

# ── 3 Compute liq_long_z ──────────────────────────────────────────────────────
cell("code", [
    "# -- 2. Compute liq_long_z (structural liquidation proxy) --------------------\n",
    "def _rz(s, w=Z_WINDOW):\n",
    "    \"\"\"Rolling z-score; NaN until window fills.\"\"\"\n",
    "    mu  = s.rolling(w, min_periods=w).mean()\n",
    "    std = s.rolling(w, min_periods=w).std(ddof=1).replace(0, np.nan)\n",
    "    return (s - mu) / std\n",
    "\n",
    "# Lower wick * volume = proxy for long-stop-sweep liquidation volume\n",
    "lower_wick = (master[['open','close']].min(axis=1) - master['low']).clip(lower=0)\n",
    "liq_raw    = lower_wick * master['volume']\n",
    "liq_long_z = _rz(liq_raw)\n",
    "liq_long_z.name = 'liq_long_z'\n",
    "\n",
    "print(f'liq_long_z non-NaN: {liq_long_z.notna().sum():,} bars')\n",
    "print(f'Mean={liq_long_z.mean():.3f}  Std={liq_long_z.std():.3f}')\n",
    "print(f'Bars > {THRESHOLD}s      : {(liq_long_z > THRESHOLD).sum():,}')\n",
    "print(f'Bars > {THRESHOLD_HIGH}s : {(liq_long_z > THRESHOLD_HIGH).sum():,}')\n",
]),

# ── 4 Fetch 1m data ────────────────────────────────────────────────────────────
cell("code", [
    "# -- 3. Identify Events & Fetch 1m OHLCV from Binance Public API -------------\n",
    "def identify_events(series, threshold, min_gap_h=MIN_EVENT_GAP):\n",
    "    \"\"\"De-clustered event timestamps where series > threshold.\"\"\"\n",
    "    cands = series[series > threshold].index\n",
    "    if len(cands) == 0:\n",
    "        return pd.DatetimeIndex([])\n",
    "    evs = [cands[0]]\n",
    "    for ts in cands[1:]:\n",
    "        if (ts - evs[-1]).total_seconds() / 3600 >= min_gap_h:\n",
    "            evs.append(ts)\n",
    "    return pd.DatetimeIndex(evs)\n",
    "\n",
    "\n",
    "def fetch_binance_1m(symbol, start_ms, end_ms, limit=1000):\n",
    "    \"\"\"Paginated 1m klines from Binance; no auth required.\"\"\"\n",
    "    all_bars, cur = [], start_ms\n",
    "    while cur < end_ms:\n",
    "        url = (f'{BINANCE_BASE}/api/v3/klines'\n",
    "               f'?symbol={symbol}&interval=1m'\n",
    "               f'&startTime={cur}&endTime={end_ms}&limit={limit}')\n",
    "        req = urllib.request.Request(url, headers={'User-Agent': 'Mozilla/5.0'})\n",
    "        with urllib.request.urlopen(req, timeout=20) as resp:\n",
    "            data = _json.loads(resp.read())\n",
    "        if not data:\n",
    "            break\n",
    "        all_bars.extend(data)\n",
    "        last_ts = data[-1][0]\n",
    "        if last_ts >= end_ms or len(data) < limit:\n",
    "            break\n",
    "        cur = last_ts + 60_000\n",
    "        _time.sleep(0.05)\n",
    "    if not all_bars:\n",
    "        return pd.DataFrame()\n",
    "    df = pd.DataFrame(all_bars, columns=[\n",
    "        'ts_open','open','high','low','close','volume',\n",
    "        'ts_close','qvol','ntrades','tbase','tquote','ign'\n",
    "    ])\n",
    "    df['ts'] = pd.to_datetime(df['ts_open'].astype('int64'), unit='ms', utc=True)\n",
    "    for c in ['open','high','low','close','volume']:\n",
    "        df[c] = df[c].astype(float)\n",
    "    return (df[['ts','open','high','low','close','volume']]\n",
    "            .drop_duplicates('ts').sort_values('ts').set_index('ts'))\n",
    "\n",
    "\n",
    "events_norm    = identify_events(liq_long_z, THRESHOLD)\n",
    "events_extreme = identify_events(liq_long_z, THRESHOLD_HIGH)\n",
    "print(f'Events > {THRESHOLD}s   : {len(events_norm):,}')\n",
    "print(f'Events > {THRESHOLD_HIGH}s : {len(events_extreme):,}')\n",
    "\n",
    "# Build batched API ranges (merge nearby windows to minimise calls)\n",
    "FETCH_MARGIN = WINDOW + 5\n",
    "_ms = lambda ts: int(ts.timestamp() * 1000)\n",
    "\n",
    "ranges = [(ev - pd.Timedelta(minutes=FETCH_MARGIN),\n",
    "           ev + pd.Timedelta(minutes=FETCH_MARGIN))\n",
    "          for ev in events_norm]\n",
    "ranges.sort(key=lambda x: x[0])\n",
    "merged_r = []\n",
    "for s, e in ranges:\n",
    "    if merged_r and s <= merged_r[-1][1] + pd.Timedelta(minutes=5):\n",
    "        merged_r[-1] = (merged_r[-1][0], max(merged_r[-1][1], e))\n",
    "    else:\n",
    "        merged_r.append([s, e])\n",
    "\n",
    "print(f'Batched API calls : {len(merged_r)}')\n",
    "frames_1m = []\n",
    "for i, (s, e) in enumerate(merged_r):\n",
    "    try:\n",
    "        chunk = fetch_binance_1m(SYMBOL, _ms(s), _ms(e))\n",
    "        if not chunk.empty:\n",
    "            frames_1m.append(chunk)\n",
    "    except Exception as exc:\n",
    "        print(f'  [warn] range {i}: {exc}')\n",
    "    if (i + 1) % 20 == 0:\n",
    "        print(f'  {i+1}/{len(merged_r)} done')\n",
    "\n",
    "price_1m = pd.DataFrame()\n",
    "if frames_1m:\n",
    "    price_1m = pd.concat(frames_1m)\n",
    "    price_1m = price_1m[~price_1m.index.duplicated()].sort_index()\n",
    "    print(f'1m bars fetched   : {len(price_1m):,}')\n",
    "    print(f'Range             : {price_1m.index.min()} to {price_1m.index.max()}')\n",
    "else:\n",
    "    print('WARNING: No 1m data fetched — check network / Binance API.')\n",
]),

# ── 5 Extract windows ──────────────────────────────────────────────────────────
cell("code", [
    "# -- 4. Extract Normalized Price Windows (+/-60 1m bars) ----------------------\n",
    "OFFSETS = np.arange(-WINDOW, WINDOW + 1)   # -60 ... +60  (121 values)\n",
    "\n",
    "def extract_windows(events, price_df, window=WINDOW):\n",
    "    \"\"\"\n",
    "    For each 1h event timestamp, snap to nearest 1m bar, extract\n",
    "    +/- window 1m closes, normalise to % return vs t=0.\n",
    "    Returns ndarray (n_events, 2*window+1); NaN where bars unavailable.\n",
    "    \"\"\"\n",
    "    if price_df.empty:\n",
    "        return np.full((len(events), 2*window+1), np.nan)\n",
    "    close  = price_df['close'].values\n",
    "    ts_map = {ts: i for i, ts in enumerate(price_df.index)}\n",
    "    rows   = []\n",
    "    offsets = np.arange(-window, window+1)\n",
    "    for ev in events:\n",
    "        ev_fl = ev.floor('1min')\n",
    "        if ev_fl not in ts_map:\n",
    "            rows.append(np.full(2*window+1, np.nan))\n",
    "            continue\n",
    "        c   = ts_map[ev_fl]\n",
    "        idx = c + offsets\n",
    "        ok  = (idx >= 0) & (idx < len(close))\n",
    "        row = np.full(2*window+1, np.nan)\n",
    "        row[ok] = close[idx[ok]]\n",
    "        p0 = row[window]\n",
    "        if np.isnan(p0) or p0 == 0:\n",
    "            rows.append(np.full(2*window+1, np.nan))\n",
    "            continue\n",
    "        rows.append((row / p0 - 1.0) * 100.0)\n",
    "    return np.array(rows)\n",
    "\n",
    "\n",
    "windows_norm    = extract_windows(events_norm,    price_1m)\n",
    "windows_extreme = extract_windows(events_extreme, price_1m)\n",
    "\n",
    "# Drop rows with >50% NaN (Binance history may not reach far back)\n",
    "def _clean(mat):\n",
    "    return mat[np.mean(np.isnan(mat), axis=1) < 0.5]\n",
    "\n",
    "windows_norm    = _clean(windows_norm)\n",
    "windows_extreme = _clean(windows_extreme)\n",
    "print(f'Usable windows >{THRESHOLD}s   : {windows_norm.shape[0]}')\n",
    "print(f'Usable windows >{THRESHOLD_HIGH}s : {windows_extreme.shape[0]}')\n",
    "\n",
    "def _stats(mat):\n",
    "    mean = np.nanmean(mat, axis=0)\n",
    "    std  = np.nanstd(mat,  axis=0)\n",
    "    n    = np.sum(~np.isnan(mat), axis=0)\n",
    "    se   = std / np.sqrt(np.maximum(n, 1))\n",
    "    return mean, std, se\n",
    "\n",
    "mean_norm, std_norm, se_norm = _stats(windows_norm)\n",
    "mean_ext,  std_ext,  se_ext  = _stats(windows_extreme)\n",
]),

# ── 6 Chart ────────────────────────────────────────────────────────────────────
cell("code", [
    "# -- 5. Main Event Study Chart (6 panels) ------------------------------------\n",
    "DARK_BG = '#0a0a0a'\n",
    "ACCENT  = '#00d4aa'\n",
    "RED     = '#ff4757'\n",
    "ORANGE  = '#ffa502'\n",
    "GRID    = '#1e1e1e'\n",
    "TEXT    = '#e0e0e0'\n",
    "\n",
    "fig = plt.figure(figsize=(18, 16), facecolor=DARK_BG)\n",
    "gs  = gridspec.GridSpec(3, 2, figure=fig, hspace=0.50, wspace=0.35)\n",
    "ax_main = fig.add_subplot(gs[0, :])\n",
    "ax_heat = fig.add_subplot(gs[1, 0])\n",
    "ax_dist = fig.add_subplot(gs[1, 1])\n",
    "ax_wr   = fig.add_subplot(gs[2, 0])\n",
    "ax_info = fig.add_subplot(gs[2, 1])\n",
    "\n",
    "for ax in [ax_main, ax_heat, ax_dist, ax_wr, ax_info]:\n",
    "    ax.set_facecolor(DARK_BG)\n",
    "    ax.tick_params(colors=TEXT, labelsize=9)\n",
    "    for spine in ax.spines.values():\n",
    "        spine.set_color(GRID)\n",
    "    ax.grid(True, color=GRID, linewidth=0.5, alpha=0.6)\n",
    "\n",
    "t = OFFSETS\n",
    "\n",
    "# Panel 1: mean price trajectory +/- 2 SE band\n",
    "ax = ax_main\n",
    "if windows_norm.shape[0] > 0:\n",
    "    ax.fill_between(t, mean_norm - 2*se_norm, mean_norm + 2*se_norm,\n",
    "                    alpha=0.15, color=ACCENT)\n",
    "    ax.plot(t, mean_norm, color=ACCENT, lw=2.0,\n",
    "            label=f'Mean +/-2SE  N={windows_norm.shape[0]}  (z>{THRESHOLD})')\n",
    "if windows_extreme.shape[0] > 0:\n",
    "    ax.fill_between(t, mean_ext - 2*se_ext, mean_ext + 2*se_ext,\n",
    "                    alpha=0.18, color=RED)\n",
    "    ax.plot(t, mean_ext, color=RED, lw=2.5, ls='--',\n",
    "            label=f'Extreme +/-2SE  N={windows_extreme.shape[0]}  (z>{THRESHOLD_HIGH})')\n",
    "ax.axvline(0, color='white', lw=1.0, ls=':')\n",
    "ax.axhline(0, color=GRID, lw=0.8)\n",
    "ax.axvspan(-WINDOW, 0, alpha=0.04, color='red')\n",
    "ax.axvspan(0, WINDOW, alpha=0.04, color='green')\n",
    "ax.set_xlabel('Offset from event (minutes)', color=TEXT, fontsize=10)\n",
    "ax.set_ylabel('Avg price return vs t=0 (%)', color=TEXT, fontsize=10)\n",
    "ax.set_title(\n",
    "    f'BTCUSDT: Average Price Trajectory +/-{WINDOW} Minutes Around liq_long_z Spike\\n'\n",
    "    f'(1m bars | threshold={THRESHOLD}s | {len(events_norm)} raw events | '\n",
    "    f'{windows_norm.shape[0]} usable)',\n",
    "    color=TEXT, fontsize=12, fontweight='bold'\n",
    ")\n",
    "ax.legend(framealpha=0.2, labelcolor=TEXT, fontsize=9)\n",
    "ax.set_xlim(-WINDOW, WINDOW)\n",
    "\n",
    "# Panel 2: heatmap of all paths\n",
    "ax = ax_heat\n",
    "if windows_norm.shape[0] > 0:\n",
    "    clip = np.nanpercentile(np.abs(windows_norm), 99)\n",
    "    im = ax.imshow(np.clip(windows_norm, -clip, clip),\n",
    "                   aspect='auto', cmap='RdYlGn',\n",
    "                   extent=[-WINDOW, WINDOW, 0, windows_norm.shape[0]],\n",
    "                   vmin=-clip, vmax=clip)\n",
    "    plt.colorbar(im, ax=ax, label='% return').ax.tick_params(colors=TEXT)\n",
    "    ax.axvline(0, color='white', lw=0.8, ls=':')\n",
    "ax.set_title('All Event Windows (heatmap)', color=TEXT, fontsize=10)\n",
    "ax.set_xlabel('Offset (minutes)', color=TEXT)\n",
    "ax.set_ylabel('Event index', color=TEXT)\n",
    "\n",
    "# Panel 3: post-event return distributions\n",
    "ax = ax_dist\n",
    "for offset, color, label in [(10,'#ffd700','+10min'),(30,ORANGE,'+30min'),(60,RED,'+60min')]:\n",
    "    if windows_norm.shape[0] > 0:\n",
    "        vals = windows_norm[:, WINDOW + offset]\n",
    "        clean = vals[~np.isnan(vals)]\n",
    "        if len(clean) > 0:\n",
    "            ax.hist(clean, bins=30, alpha=0.5, color=color, label=label, density=True)\n",
    "ax.axvline(0, color='white', lw=1.0, ls=':')\n",
    "ax.set_title('Post-Event Return Distribution', color=TEXT, fontsize=10)\n",
    "ax.set_xlabel('% return vs t=0', color=TEXT)\n",
    "ax.set_ylabel('Density', color=TEXT)\n",
    "ax.legend(framealpha=0.2, labelcolor=TEXT, fontsize=8)\n",
    "\n",
    "# Panel 4: % events where price falls (SHORT signal quality curve)\n",
    "ax = ax_wr\n",
    "if windows_norm.shape[0] > 0:\n",
    "    post = windows_norm[:, WINDOW:]\n",
    "    wr   = np.nanmean(post < 0, axis=0) * 100\n",
    "    xax  = np.arange(0, WINDOW + 1)\n",
    "    ax.plot(xax, wr, color=ACCENT, lw=1.8)\n",
    "    ax.axhline(50, color='white', lw=0.8, ls='--', alpha=0.4)\n",
    "    ax.fill_between(xax, wr, 50, where=(wr > 50), alpha=0.20, color=RED,\n",
    "                    label='Falls more often')\n",
    "    ax.fill_between(xax, wr, 50, where=(wr <= 50), alpha=0.20, color=ACCENT,\n",
    "                    label='Rises more often')\n",
    "ax.set_title('% Events Where Price Falls Post-Event\\n(SHORT signal quality)', color=TEXT, fontsize=10)\n",
    "ax.set_xlabel('Minutes after event', color=TEXT)\n",
    "ax.set_ylabel('% events price falls', color=TEXT)\n",
    "ax.set_ylim(0, 100)\n",
    "ax.yaxis.set_major_formatter(mticker.FuncFormatter(lambda v, _: f'{v:.0f}%'))\n",
    "ax.legend(framealpha=0.2, labelcolor=TEXT, fontsize=8)\n",
    "\n",
    "# Panel 5: stats table\n",
    "ax = ax_info\n",
    "ax.axis('off')\n",
    "def _fmt(offset):\n",
    "    if windows_norm.shape[0] == 0:\n",
    "        return 'N/A', 'N/A', 'N/A'\n",
    "    v = windows_norm[:, WINDOW + offset]\n",
    "    v = v[~np.isnan(v)]\n",
    "    if len(v) < 3:\n",
    "        return 'N/A', 'N/A', 'N/A'\n",
    "    return (f'{np.mean(v):+.3f}%', f'{np.median(v):+.3f}%', f'{np.mean(v<0)*100:.1f}%')\n",
    "\n",
    "table_data = [_fmt(off) for off in [5, 10, 20, 30, 45, 60]]\n",
    "table_rows = [[lbl, *row] for lbl, row in\n",
    "              zip(['+5m','+10m','+20m','+30m','+45m','+60m'], table_data)]\n",
    "tbl = ax.table(cellText=table_rows,\n",
    "               colLabels=['Horizon','Mean ret','Median ret','% fell'],\n",
    "               cellLoc='center', loc='center', bbox=[0, 0.1, 1, 0.8])\n",
    "tbl.auto_set_font_size(False)\n",
    "tbl.set_fontsize(9)\n",
    "for (r, c), cell in tbl.get_celld().items():\n",
    "    cell.set_facecolor('#1a1a2e' if r == 0 else DARK_BG)\n",
    "    cell.set_text_props(color=TEXT)\n",
    "    cell.set_edgecolor(GRID)\n",
    "ax.set_title('Post-Event Statistics (1m resolution)', color=TEXT, fontsize=10)\n",
    "\n",
    "fig.suptitle(\n",
    "    'Jose / Risk Manager  --  Liquidation Cascade Event Study  (+/-60 min, 1m bars)',\n",
    "    y=0.997, color=TEXT, fontsize=13, fontweight='bold'\n",
    ")\n",
    "out_path = OUT_DIR / 'liq_impact_analysis_1m.png'\n",
    "fig.savefig(out_path, dpi=150, bbox_inches='tight', facecolor=DARK_BG)\n",
    "plt.close(fig)\n",
    "print(f'Chart saved -> {out_path}')\n",
]),

# ── 7 Stats table ──────────────────────────────────────────────────────────────
cell("code", [
    "# -- 6. Statistical Summary Table ---------------------------------------------\n",
    "print('=' * 72)\n",
    "print('LIQUIDATION CASCADE IMPACT -- MINUTE-LEVEL STATISTICAL SUMMARY')\n",
    "print('=' * 72)\n",
    "print(f'Dataset  : BTCUSDT 1h  '\n",
    "      f'{master.index.min().date()} to {master.index.max().date()}')\n",
    "print(f'Price    : 1m bars from Binance public REST API')\n",
    "print(f'Window   : +/-{WINDOW} minutes  ({WINDOW*2+1} 1m bars per event)')\n",
    "print(f'Threshold: liq_long_z > {THRESHOLD} sigma')\n",
    "print(f'Events   : {len(events_norm):,} raw  ->  '\n",
    "      f'{windows_norm.shape[0]:,} usable (>=50% data coverage)')\n",
    "print()\n",
    "hdr = f\"{'Horizon':>8}  {'Mean%':>9}  {'Median%':>9}  {'Std%':>8}  {'P(fall)':>7}  {'t-stat':>7}\"\n",
    "print(hdr)\n",
    "print('-' * len(hdr))\n",
    "for offset in [1, 5, 10, 15, 20, 30, 45, 60]:\n",
    "    if windows_norm.shape[0] == 0:\n",
    "        break\n",
    "    vals  = windows_norm[:, WINDOW + offset]\n",
    "    clean = vals[~np.isnan(vals)]\n",
    "    if len(clean) < 3:\n",
    "        continue\n",
    "    m  = np.mean(clean)\n",
    "    md = np.median(clean)\n",
    "    s  = np.std(clean, ddof=1)\n",
    "    p  = np.mean(clean < 0) * 100\n",
    "    t  = m / (s / np.sqrt(len(clean)))\n",
    "    print(f'+{offset:>6}m  {m:>+9.4f}  {md:>+9.4f}  {s:>8.4f}  '\n",
    "          f'{p:>6.1f}%  {t:>+7.3f}')\n",
]),

# ── 8 Half-life ────────────────────────────────────────────────────────────────
cell("code", [
    "# -- 7. Alpha Half-Life Estimation (minute-level) ----------------------------\n",
    "from scipy.optimize import curve_fit\n",
    "\n",
    "def exp_decay(t, A, tau):\n",
    "    return A * np.exp(-t / tau)\n",
    "\n",
    "if windows_norm.shape[0] >= 5:\n",
    "    post     = windows_norm[:, WINDOW:]\n",
    "    abs_mean = np.abs(np.nanmean(post, axis=0))\n",
    "    t_arr    = np.arange(0, WINDOW + 1, dtype=float)\n",
    "    mask     = (t_arr >= 1) & (abs_mean > 0)\n",
    "    try:\n",
    "        popt, _ = curve_fit(exp_decay, t_arr[mask], abs_mean[mask],\n",
    "                            p0=[abs_mean[mask][0], 15.0], maxfev=5000)\n",
    "        A_fit, tau_fit = popt\n",
    "        half_life = tau_fit * np.log(2)\n",
    "        print(f'Exponential decay fit   A={A_fit:.4f}%  tau={tau_fit:.1f}min')\n",
    "        print(f'Alpha half-life         = {half_life:.1f} minutes')\n",
    "        if half_life < 5:\n",
    "            msg = '< 5min -- must execute within the same 1m candle'\n",
    "        elif half_life < 20:\n",
    "            msg = f'~{half_life:.0f}min -- viable for 5m entries'\n",
    "        else:\n",
    "            msg = f'> 20min -- viable for 15m-1h entries'\n",
    "        print(f'Risk implication        : {msg}')\n",
    "    except RuntimeError as e:\n",
    "        print(f'Curve fit failed: {e}')\n",
    "else:\n",
    "    print('Insufficient events for half-life estimation.')\n",
]),

# ── 9 Conclusions ─────────────────────────────────────────────────────────────
cell("markdown", [
    "## 8. Risk Management Conclusions (Jose)\n",
    "\n",
    "### What the Minute-Level Event Study Shows\n",
    "\n",
    "| Observation | Risk Management Implication |\n",
    "|---|---|\n",
    "| **Pre-event (t=-60 to t=0)**: gradual price decline precedes spike | Cascade is a **continuation** signal -- do NOT enter long before liq_long_z fires |\n",
    "| **t=0**: liq_long_z > 2sigma spike detected on 1h bar | Event trigger -- check post-event win rate before entry |\n",
    "| **Post-event (t=0 to +10min)**: sharp directional move | Immediate SHORT window if >55% of events show price drop |\n",
    "| **Half-life < 20min** | Entry must occur within 1-2 candles of event; delayed entries miss edge |\n",
    "| **Extreme events (z>3s) show larger magnitude** | Use `THRESHOLD_HIGH=3.0` for cleaner signal with higher conviction |\n",
    "\n",
    "### Kill Switch / Position Sizing Rules\n",
    "- `liq_long_z > 3sigma` AND post-event WR > 60% -> allow **0.5x normal position** SHORT entry\n",
    "- SL = **0.5x ATR** (tight -- microstructure signal decays fast)\n",
    "- TP = **1.5x ATR**, max hold = **15-20 minutes** (per measured half-life)\n",
    "- **Kill switch trigger**: liq_long_z > 4sigma on BTC+ETH simultaneously -> reduce ALL leverage to 1x, halt new entries\n",
    "\n",
    "### Revision Note\n",
    "> Previous analysis used +/-60 **hourly** bars (= +/-2.5 days window), which obscures microstructure dynamics.  \n",
    "> This version uses +/-60 **minute** bars (1m Binance data), correctly capturing the fast decay of liquidation cascade signals.",
]),

]  # end cells list

nb = {
    "cells": cells,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3",
        },
        "language_info": {"name": "python", "version": "3.10.0"},
    },
    "nbformat": 4,
    "nbformat_minor": 5,
}

with open(NB_PATH, "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

print(f"Written: {NB_PATH}")
print(f"Cells  : {len(cells)}")
