"""Base interfaces for institutional portfolio models."""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

import numpy as np
import pandas as pd


# ----------------------------------------------------

@dataclass
class TargetAllocation:
    """Target portfolio weights from a model."""
    weights: Dict[str, float]  # symbol -> weight (-1..1, negative = short)
    regime: str = ""           # current regime label (if applicable)
    signal_strength: float = 1.0
    meta: Dict[str, Any] = field(default_factory=dict)

    @property
    def gross_exposure(self) -> float:
        return sum(abs(w) for w in self.weights.values())

    @property
    def net_exposure(self) -> float:
        return sum(self.weights.values())

    @property
    def symbols(self) -> List[str]:
        return list(self.weights.keys())


@dataclass
class RebalanceOrder:
    """Order generated by rebalance logic."""
    symbol: str
    side: str       # buy / sell
    qty: float      # in base units
    weight: float   # target weight
    reason: str = ""


# ----------------------------------------------------

@dataclass
class PortfolioState:
    """Multi-asset portfolio snapshot."""
    equity: float = 10000.0
    cash: float = 10000.0
    positions: Dict[str, float] = field(default_factory=dict)     # symbol -> qty
    avg_entries: Dict[str, float] = field(default_factory=dict)   # symbol -> avg price
    weights: Dict[str, float] = field(default_factory=dict)       # symbol -> current weight
    unrealized_pnl: float = 0.0
    realized_pnl: float = 0.0
    total_trades: int = 0
    max_equity: float = 10000.0
    max_drawdown: float = 0.0

    def position_value(self, symbol: str, price: float) -> float:
        return self.positions.get(symbol, 0.0) * price

    def gross_exposure(self, prices: Dict[str, float]) -> float:
        return sum(abs(self.positions.get(s, 0) * p) for s, p in prices.items())


# ----------------------------------------------------

class PortfolioModel(ABC):
    """Base class for all institutional model families."""

    name: str = "base_model"
    group: str = "quant"

    def __init__(self, cfg: Dict[str, Any]):
        self.cfg = cfg
        self.params = cfg.get("params", {})
        self.universe: List[str] = cfg.get("universe", [])

    @abstractmethod
    def fit(self, data: Dict[str, pd.DataFrame]) -> None:
        """Fit model on historical data. data = {symbol: ohlcv_df}."""
        pass

    @abstractmethod
    def compute_targets(self, data: Dict[str, pd.DataFrame]) -> TargetAllocation:
        """Compute target weights given current data window."""
        pass

    def rebalance(
        self,
        state: PortfolioState,
        prices: Dict[str, float],
        targets: TargetAllocation,
    ) -> List[RebalanceOrder]:
        """Convert target weights into orders to execute.
        Default implementation: compute weight delta -> orders.
        """
        orders = []
        equity = state.equity

        for symbol, target_w in targets.weights.items():
            price = prices.get(symbol, 0.0)
            if price <= 0:
                continue

            # Current weight
            current_qty = state.positions.get(symbol, 0.0)
            current_value = current_qty * price
            current_w = current_value / equity if equity > 0 else 0.0

            # Delta
            delta_w = target_w - current_w
            delta_value = delta_w * equity
            delta_qty = delta_value / price

            # Minimum order threshold (0.1% of equity)
            if abs(delta_value) < equity * 0.001:
                continue

            if delta_qty > 0:
                orders.append(RebalanceOrder(
                    symbol=symbol, side="buy", qty=abs(delta_qty),
                    weight=target_w, reason=targets.meta.get("reason", "rebalance"),
                ))
            elif delta_qty < 0:
                orders.append(RebalanceOrder(
                    symbol=symbol, side="sell", qty=abs(delta_qty),
                    weight=target_w, reason=targets.meta.get("reason", "rebalance"),
                ))

        return orders


# ----------------------------------------------------

class RebalanceScheduler:
    """Determines when to rebalance based on frequency config."""

    def __init__(self, frequency: str = "weekly"):
        self.frequency = frequency
        self._last_rebalance_idx: int = -999
        self._bar_count: int = 0

    def should_rebalance(self, idx: int, ts: Optional[pd.Timestamp] = None) -> bool:
        """Check if we should rebalance at this bar index."""
        self._bar_count = idx

        if self.frequency == "daily":
            period = 1
        elif self.frequency == "weekly":
            period = 5
        elif self.frequency == "monthly":
            period = 21
        elif self.frequency == "biweekly":
            period = 10
        else:
            period = int(self.frequency) if self.frequency.isdigit() else 5

        if idx - self._last_rebalance_idx >= period:
            self._last_rebalance_idx = idx
            return True
        return False

    def bars_until_next(self) -> int:
        if self.frequency == "daily":
            period = 1
        elif self.frequency == "weekly":
            period = 5
        elif self.frequency == "monthly":
            period = 21
        elif self.frequency == "biweekly":
            period = 10
        else:
            period = int(self.frequency) if self.frequency.isdigit() else 5
        return max(0, period - (self._bar_count - self._last_rebalance_idx))


# ----------------------------------------------------

class MultiAssetBroker:
    """Paper broker that handles multiple assets."""

    def __init__(self, cfg: Dict[str, Any]):
        initial = cfg.get("app", {}).get("initial_equity", 30.0)
        self.fee_bps = cfg.get("execution", {}).get("fee_bps", 6)
        self.slip_bps = cfg.get("execution", {}).get("slippage_bps", 2)
        self._state = PortfolioState(
            equity=initial, cash=initial, max_equity=initial,
        )
        self.trade_log: List[Dict[str, Any]] = []
        self._halted = False

    def state(self) -> PortfolioState:
        return self._state

    def is_halted(self) -> bool:
        return self._halted

    def halt(self):
        self._halted = True

    def resume(self):
        self._halted = False

    def update_mark_prices(self, prices: Dict[str, float]):
        """Mark-to-market all positions."""
        s = self._state
        total_value = s.cash
        for sym, qty in s.positions.items():
            px = prices.get(sym, 0.0)
            total_value += qty * px

        s.equity = total_value
        s.unrealized_pnl = total_value - s.cash - sum(
            s.avg_entries.get(sym, 0) * qty for sym, qty in s.positions.items()
        )

        # Update weights
        for sym in s.positions:
            px = prices.get(sym, 0.0)
            s.weights[sym] = (s.positions[sym] * px) / s.equity if s.equity > 0 else 0.0

        # Drawdown
        if s.equity > s.max_equity:
            s.max_equity = s.equity
        dd = (s.max_equity - s.equity) / s.max_equity if s.max_equity > 0 else 0
        if dd > s.max_drawdown:
            s.max_drawdown = dd

    def execute_rebalance(
        self, orders: List[RebalanceOrder], prices: Dict[str, float], ts: str = ""
    ) -> List[Dict[str, Any]]:
        """Execute rebalance orders. Returns list of fill dicts."""
        if self._halted:
            return []

        fills = []
        s = self._state

        for order in orders:
            price = prices.get(order.symbol, 0.0)
            if price <= 0 or order.qty <= 0:
                continue

            # Slippage
            if order.side == "buy":
                fill_price = price * (1 + self.slip_bps / 10000.0)
            else:
                fill_price = price * (1 - self.slip_bps / 10000.0)

            fee = fill_price * order.qty * (self.fee_bps / 10000.0)
            notional = fill_price * order.qty

            # Track PnL
            trade_pnl = 0.0
            current_qty = s.positions.get(order.symbol, 0.0)
            avg = s.avg_entries.get(order.symbol, fill_price)

            if order.side == "buy":
                # Cash outflow for buy
                s.cash -= notional + fee

                if current_qty >= 0:
                    # Opening/adding long
                    new_qty = current_qty + order.qty
                    if new_qty > 0:
                        new_avg = (current_qty * avg + order.qty * fill_price) / new_qty
                        s.positions[order.symbol] = new_qty
                        s.avg_entries[order.symbol] = new_avg
                else:
                    # Closing short (partially or fully), possibly flipping long
                    close_qty = min(order.qty, abs(current_qty))
                    fee_close = fee * (close_qty / order.qty)
                    trade_pnl = (avg - fill_price) * close_qty - fee_close
                    s.realized_pnl += trade_pnl
                    new_qty = current_qty + order.qty  # current_qty is negative
                    if new_qty < 0:
                        s.positions[order.symbol] = new_qty
                        s.avg_entries[order.symbol] = avg
                    elif new_qty == 0:
                        s.positions.pop(order.symbol, None)
                        s.avg_entries.pop(order.symbol, None)
                    else:
                        # Flipped to long with remaining qty
                        s.positions[order.symbol] = new_qty
                        s.avg_entries[order.symbol] = fill_price

            elif order.side == "sell":
                # Cash inflow for sell
                s.cash += notional - fee

                if current_qty <= 0:
                    # Opening/adding short
                    new_qty = current_qty - order.qty
                    if new_qty < 0:
                        new_avg = (abs(current_qty) * avg + order.qty * fill_price) / abs(new_qty)
                        s.positions[order.symbol] = new_qty
                        s.avg_entries[order.symbol] = new_avg
                else:
                    # Closing long (partially or fully), possibly flipping short
                    close_qty = min(order.qty, current_qty)
                    fee_close = fee * (close_qty / order.qty)
                    trade_pnl = (fill_price - avg) * close_qty - fee_close
                    s.realized_pnl += trade_pnl
                    new_qty = current_qty - order.qty
                    if new_qty > 0:
                        s.positions[order.symbol] = new_qty
                        s.avg_entries[order.symbol] = avg
                    elif new_qty == 0:
                        s.positions.pop(order.symbol, None)
                        s.avg_entries.pop(order.symbol, None)
                    else:
                        # Flipped to short with remaining qty
                        s.positions[order.symbol] = new_qty
                        s.avg_entries[order.symbol] = fill_price

            s.total_trades += 1

            fill = {
                "ts": ts, "symbol": order.symbol, "side": order.side,
                "price": fill_price, "qty": order.qty, "fee": fee,
                "slippage": abs(fill_price - price) * order.qty,
                "pnl": trade_pnl, "weight": order.weight,
                "reason": order.reason,
            }
            self.trade_log.append(fill)
            fills.append(fill)

        # Clean zero positions
        s.positions = {k: v for k, v in s.positions.items() if abs(v) > 1e-12}
        s.avg_entries = {k: v for k, v in s.avg_entries.items() if k in s.positions}

        return fills

    def close_all(self, prices: Dict[str, float], ts: str = "") -> List[Dict[str, Any]]:
        """Flatten all positions."""
        orders = []
        for sym, qty in list(self._state.positions.items()):
            if qty > 0:
                orders.append(RebalanceOrder(sym, "sell", abs(qty), 0.0, "close_all"))
            elif qty < 0:
                orders.append(RebalanceOrder(sym, "buy", abs(qty), 0.0, "close_all"))
        return self.execute_rebalance(orders, prices, ts)

    def report(self) -> Dict[str, Any]:
        s = self._state
        return {
            "equity": round(s.equity, 4),
            "cash": round(s.cash, 4),
            "positions": {k: round(v, 8) for k, v in s.positions.items()},
            "weights": {k: round(v, 4) for k, v in s.weights.items()},
            "realized_pnl": round(s.realized_pnl, 4),
            "unrealized_pnl": round(s.unrealized_pnl, 4),
            "total_trades": s.total_trades,
            "max_drawdown": round(s.max_drawdown, 6),
            "gross_exposure": round(sum(abs(v) for v in s.weights.values()), 4),
        }
